---
k3s_version: v1.26.1+k3s1
ansible_user: root
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
k3s_private_registry: |
  mirrors:
    docker.io:
      endpoint:
        -  https://dockerhub.azk8s.cn